import type { NextPage } from 'next';
import { useRouter } from 'next/router';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

const Air: NextPage = () => {
  const router = useRouter();
  const { currency } = router.query;
  let title: string = 'Click to name your card';
  let address: string = '21345rdfghjhgfds';

  const addressToClipboard = () => {
    navigator.clipboard.writeText(address);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Air - Coinplus</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <main className={styles.main}>
        <section>
          <Image className="logo" src="/img/logo.png" alt="" width={329} height={316} />
          <h1 id="title" className="title">
            {title}
          </h1>
          <Image id="qrcode" className="qrcode" src="" alt="" />
          <span id="address" className="address">
            {address}
          </span>
          <button onClick={addressToClipboard}>COPY ADDRESS</button>
        </section>

        <section className="balance">
          <div>
            <span id="balance__total" className="balance__total">
              Not Available
            </span>{' '}
            <span id="balance__unconfirmed"></span>
            <span className="balance__token" id="token"></span>
          </div>
          <a href="#" id="balance__history" className="balance_history" target="_blank">
            History of transactions
          </a>
          <a href="#" id="balance__tokens" className="balance_tokens" target="_blank">
            View my tokens
          </a>
        </section>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/img/logo.png" alt="Coinplus Logo" width={16.658227848} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Air;
